[build]
publish = ".next"

[[plugins]]
package = "@netlify/next-runtime"

[[redirects]]
from = "/_next/image*"
query = { url = ":url", w = ":width", h = ":height", q = ":quality" }
to = "/.netlify/images?url=:url&w=:width&h=:height&q=:quality"
status = 200